# Generated by Django 2.0.7 on 2022-04-16 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_cart', '0003_auto_20190427_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartinfo',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterField(
            model_name='cartinfo',
            name='count',
            field=models.IntegerField(default=0, verbose_name='products_count'),
        ),
        migrations.AlterField(
            model_name='cartinfo',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo', verbose_name='products'),
        ),
        migrations.AlterField(
            model_name='cartinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo', verbose_name='User'),
        ),
    ]
