# Generated by Django 2.0.7 on 2022-04-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0006_auto_20190427_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='usecurity_answer',
            field=models.CharField(default='', max_length=30, verbose_name='安全答案'),
        ),
    ]
