# Generated by Django 2.0.7 on 2022-04-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0006_auto_20190427_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='usanswer',
            field=models.CharField(default='', max_length=40, verbose_name='Security question answer'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='usquestion',
            field=models.CharField(default='', max_length=40, verbose_name='Security question'),
        ),
    ]
