# Generated by Django 2.0.7 on 2022-04-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0009_auto_20220411_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ufullname',
            field=models.CharField(default='', max_length=30, verbose_name='name'),
        ),
    ]
