# Generated by Django 2.0.7 on 2022-04-12 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0010_userinfo_ufullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='usquestion',
            new_name='uquestion',
        ),
    ]
