# Generated by Django 2.0.7 on 2022-04-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0011_auto_20220412_0053'),
        ('df_user', '0012_auto_20220411_2110'),
    ]

    operations = [
    ]
