# Generated by Django 2.0.7 on 2022-04-14 16:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0013_merge_20220414_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsbrowser',
            options={'verbose_name': 'browser_history', 'verbose_name_plural': 'browser_history'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'User_Info', 'verbose_name_plural': 'User_Info'},
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='usanswer',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='usquestion',
        ),
        migrations.AlterField(
            model_name='goodsbrowser',
            name='browser_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='browse_item'),
        ),
        migrations.AlterField(
            model_name='goodsbrowser',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo', verbose_name='goods_ID'),
        ),
        migrations.AlterField(
            model_name='goodsbrowser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo', verbose_name='user_ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uaddress',
            field=models.CharField(default='', max_length=100, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uanswer',
            field=models.CharField(default='', max_length=30, verbose_name='security_answer'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uemail',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='ufullname',
            field=models.CharField(default='', max_length=30, verbose_name='full_name'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uname',
            field=models.CharField(max_length=20, unique=True, verbose_name='user_nmae'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uphone',
            field=models.CharField(default='', max_length=11, verbose_name='phone_num'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='upwd',
            field=models.CharField(max_length=40, verbose_name='user_pwd'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uquestion',
            field=models.CharField(default='', max_length=40, verbose_name='security_question'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uyoubian',
            field=models.CharField(default='', max_length=6, verbose_name='zip_code'),
        ),
    ]
