# Generated by Django 2.0.7 on 2022-04-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0003_auto_20220416_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='ocontact',
            field=models.CharField(default='', max_length=11, verbose_name='receiver_phone'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='oreceiver',
            field=models.CharField(default='', max_length=20, verbose_name='order_receiver'),
        ),
    ]
